version: '3'

services:
  database:
    image: mysql:${MYSQL_VERSION:-8.0}
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-symfoprojet3}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Root8888!}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Root8888!}
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql:rw
      # Vous pouvez utiliser un répertoire hôte monté à la place pour éviter de supprimer accidentellement le volume et perdre toutes vos données.
      # - ./docker/db/data:/var/lib/mysql:rw
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]

volumes:
  database_data:
